name: Build APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Deps
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk zip unzip
          pip install buildozer cython==0.29.33
      - name: Build APK
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: stable
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: quiz-masti-apk
          path: bin/*.apk
